name: Build Baryon
on:
  release:
jobs:
  build:
    strategy:
      matrix:
        architecture: [amd64, arm64]
        platform: [darwin, linux, windows]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Go
        run: |
          curl -OL https://go.dev/dl/go1.22.1.linux-amd64.tar.gz
          rm -rf /usr/local/go 
          sudo tar -C /usr/local -xzf go1.22.1.linux-amd64.tar.gz
      - name: Build
        run: |
          GOOS=${{ matrix.platform }} GOARCH=${{ matrix.architecture }} go build -o baryon-lang .
      - uses: vimtor/action-zip@v1.2
        with:
          files: baryon-lang
          dest: baryon-lang_${{ matrix.platform }}_${{ matrix.architecture }}_${{ github.event.release.tag_name }}.zip
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            baryon-lang_*.zip
